package lambkin:common-core@0.1.0;

interface types {
  type bytes = list<u8>;
  type utf8 = list<u8>;
  type offset = u32;

  resource text {
    open: static func(initial: utf8) -> result<text, string>;
    clone: func() -> result<text, string>;
    insert: func(offset: offset, utf8: utf8) -> result<_, string>;
    delete: func(start: offset, end: offset) -> result<_, string>;
    export: func() -> result<utf8, string>;
    drop: func() -> result<_, string>;
  }

  type status = result<_, string>;

  type db-op-result = result<db, string>;
  type txn-op-result = result<txn, string>;
  type kv-get-result = result<option<bytes>, string>;

  @croft-lower-group(store)
  resource db {
    open: static func(page-size: u32) -> db-op-result;
    drop: func() -> status;
    begin: func(read-only: bool) -> txn-op-result;
  }

  @croft-lower-group(store)
  resource txn {
    commit: func() -> status;
    abort: func() -> status;
    put: func(key: bytes, value: bytes) -> status;
    get: func(key: bytes) -> kv-get-result;
  }

  type mailbox-recv-result = result<option<bytes>, string>;

  resource mailbox {
    open: static func(max-messages: u32) -> result<mailbox, string>;
    send: func(payload: bytes) -> status;
    recv: func() -> mailbox-recv-result;
    drop: func() -> status;
  }
}

world common-core {
  export types;
}
