package lambkin:host-fs@0.1.0;

interface types {
  resource file;

  record fs-file-open {
    path: list<u8>,
    write: bool,
    create: bool,
    truncate: bool,
    append: bool,
  }

  record fs-file-close {
    file: file,
  }

  record fs-file-read-all {
    file: file,
  }

  type fs-file-op-result = result<file, string>;
  type fs-status = result<_, string>;
  type fs-file-read-result = result<list<u8>, string>;

  variant fs-command {
    open(fs-file-open),
    close(fs-file-close),
    read-all(fs-file-read-all),
  }

  variant fs-reply {
    file(fs-file-op-result),
    status(fs-status),
    read(fs-file-read-result),
  }
}

world host-fs {
  export types;
}
