package lambkin:host-editor-input@0.1.0;

interface host-editor-input {
  flags motion-flags {
    selecting,
    word,
    word-part,
  }

  flags delete-flags {
    word,
    word-part,
  }

  record key-event {
    key: s32,
    action: s32,
    modifiers: u32,
  }

  record char-event {
    codepoint: u32,
  }

  record menu-action {
    action-id: s32,
  }

  record motion {
    flags: motion-flags,
  }

  record deletion {
    flags: delete-flags,
  }

  variant editor-action {
    move-left(motion),
    move-right(motion),
    move-up(motion),
    move-down(motion),
    move-home(motion),
    move-end(motion),
    delete-left(deletion),
    delete-right(deletion),
    fold,
    unfold,
    indent,
    outdent,
    insert-codepoint(u32),
    undo,
    redo,
    select-all,
    copy,
    cut,
    paste,
    save,
    quit,
  }

  type status = result<_, string>;
  type action-result = result<option<editor-action>, string>;

  window-key: func(event: key-event) -> status;
  window-char: func(event: char-event) -> status;
  menu-action: func(action: menu-action) -> status;
  next-action: func() -> action-result;
}

world host-editor-input {
  export host-editor-input;
}
