package lambkin:host-fs@0.1.0;

interface host-fs {
  type fs-file-op-result = result<file, string>;
  type fs-status = result<_, string>;
  type fs-file-read-result = result<list<u8>, string>;

  resource file {
    open: static func(path: list<u8>, write: bool, create: bool, truncate: bool, append: bool) -> fs-file-op-result;
    close: func() -> fs-status;
    read-all: func() -> fs-file-read-result;
  }
}

world host-fs {
  export host-fs;
}
