package lambkin:host-clipboard@0.1.0;

interface types {
  type utf8 = list<u8>;

  type status = result<_, string>;
  type text-result = result<option<string>, string>;

  get-text: func() -> text-result;
  set-text: func(utf8: utf8) -> status;
}

world host-clipboard {
  export types;
}
