package lambkin:host-menu@0.1.0;

interface types {
  flags modifiers {
    shift,
    ctrl,
    alt,
    cmd,
  }

  record menu-item {
    action-id: s32,
    parent-action-id: s32,
    label: list<u8>,
    shortcut: option<list<u8>>,
    mods: modifiers,
  }

  type status = result<_, string>;
  type action-result = result<option<s32>, string>;

  begin-update: func() -> status;
  add-item: func(item: menu-item) -> status;
  commit-update: func() -> status;
  next-action: func() -> action-result;
}

world host-menu {
  export types;
}
