#ifndef CROFT_EDITOR_MENU_IDS_H
#define CROFT_EDITOR_MENU_IDS_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum croft_editor_menu_action_id {
    CROFT_EDITOR_MENU_APP_ROOT = 1,
    CROFT_EDITOR_MENU_FILE_ROOT = 10,
    CROFT_EDITOR_MENU_EDIT_ROOT = 20,
    CROFT_EDITOR_MENU_OPEN = 100,
    CROFT_EDITOR_MENU_SAVE = 101,
    CROFT_EDITOR_MENU_SAVE_AS = 102,
    CROFT_EDITOR_MENU_QUIT = 199,
    CROFT_EDITOR_MENU_UNDO = 201,
    CROFT_EDITOR_MENU_REDO = 202,
    CROFT_EDITOR_MENU_SELECT_ALL = 203,
    CROFT_EDITOR_MENU_COPY = 204,
    CROFT_EDITOR_MENU_CUT = 205,
    CROFT_EDITOR_MENU_PASTE = 206,
    CROFT_EDITOR_MENU_FIND = 207,
    CROFT_EDITOR_MENU_FIND_NEXT = 208,
    CROFT_EDITOR_MENU_FIND_PREVIOUS = 209,
    CROFT_EDITOR_MENU_INDENT = 210,
    CROFT_EDITOR_MENU_OUTDENT = 211,
    CROFT_EDITOR_MENU_FOLD = 212,
    CROFT_EDITOR_MENU_UNFOLD = 213,
    CROFT_EDITOR_MENU_REPLACE = 214,
    CROFT_EDITOR_MENU_REPLACE_NEXT = 215,
    CROFT_EDITOR_MENU_REPLACE_ALL = 216
} croft_editor_menu_action_id;

#ifdef __cplusplus
}
#endif

#endif /* CROFT_EDITOR_MENU_IDS_H */
