#ifndef CROFT_EDITOR_TYPOGRAPHY_H
#define CROFT_EDITOR_TYPOGRAPHY_H

#define CROFT_EDITOR_MONOSPACE_FONT_FAMILY "Menlo"
#define CROFT_EDITOR_MONOSPACE_FONT_REGULAR "Menlo-Regular"
#define CROFT_EDITOR_MONOSPACE_FONT_BOLD "Menlo-Bold"

#endif
